version: '3.4'

services:
  app:
    build:
      context: .
    ports:
        - '8000:80'
    environment: 
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      - sqldb

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ThisPasswordIsVGr8!